language: node_js
node_js: '12'
branches:
  only:
  - master
cache:
  directories:
  - node_modules
before_install:
  - npm update
install:
  - npm install
git:
  depth: 100
deploy:
  provider: heroku
  api_key:
    secure: XIDV0Mc9mDtDMAhmr6t3wybj2dUgK2Xm7Lq059RMX+fHtl3ltiyXKpKmQqM+OmdzQrD6/DnZQ86XbbHwKNirenoIjqFI3x5ynPjd3X6HxfOmvyJpLXIbKPy+H+1sieYDuzZ+KU/j6y4q7wQNUYPn+pv9cKiFN10lriXqC9V1CciuhsxfUO0qWdty4Avcoocy7vHS2Zb1R0JKzw8WH/uBemMtnPkfeBJ+c8nH1mYP/yqYnpOcBGxFLvuxRzlJiUyNwx27bdvLC1RBuHEZWlePnXbTkC8cxm+3/v6wCmcAM/gIoLWHfuDfICAg9wX/s4e/IIiiDfheaWqjSn6hD59bolsrl0vGwflX0FbRrMPBtFF2TfwcNz+TISYYwSXxxbNGhKrdk7FSpfMS4tsU2Xh9MpwvMRW3gq5YocS6IESiZgZLUglEJ2gj0SyqHQBGHlJyXX1KXHsrcjAlqi6QCDsGJTaF6K9iJI2XHaPXUtlVLX1OWtCN+VY5iaMdCaJw+q8dtPwrKvt4Gp9+q8LtsIkcvjzx0iY9FYtudp2hcuVJlEJ69x2c9MqYJo+IVunu0EbcrRpRL+unV6SXi+Z+gWglDSCRa+daO54wQeJ2HNK28o7L+neeoRMqHP1Xz8ENIQ25HoK8PxeqbHMuqf5H1yelR0nQcz4fSIXOzlXUlBt4JFE=
  app: note_taker