language: node_js
node_js: '12'
branches:
  only:
  - master
cache:
  directories:
  - node_modules
before_install:
- npm update
install:
- npm install
script:

deploy:
  provider: heroku
  api_key:
    secure: 149b0ade-1fd0-4a71-a14f-6dc7855c13c1
  app: note-taker-das